[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoclib = { path = "../AoCLib" }
good_lp = { version = "1.14.2", features = ["minilp"] }
microlp = "0.2.11"
